project:
  title: ""
  type: website
  output-dir: docs

editor: visual

website:
  title: ""      
  navbar:
    left: []                
    right:
      - text: Home
        href: index.qmd
      - text: About me
        href: About.qmd
      - text: Research
        href: Research.qmd
      #- text: Posts
      #  href: News.qmd
      - text: Publications
        href: Publication.qmd
      - text: Contact
        href: Contact.qmd
      - text: CV
        href: CV.qmd


format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    page-layout: full

